import { z } from "zod";

/**
 * Single source of truth for product data shape.
 * Edit data/products.json (generated by scripts/build-products.ts) — this file
 * guarantees the shape is valid at build time, so a malformed entry fails loudly.
 */

// Every user-facing string is bilingual (English + Hindi).
export const localizedSchema = z.object({
  en: z.string().min(1),
  hi: z.string().min(1),
});
export type Localized = z.infer<typeof localizedSchema>;

// Product categories — all 12 from the real Ganga Agro / Ammedi range.
export const categorySchema = z.enum([
  "hawan-samagri",
  "havan-samidha",
  "pooja-items",
  "pooja-moli",
  "incense-dhoop",
  "incense-sticks",
  "camphor-tablet",
  "cotton-wicks",
  "sandalwood",
  "briquettes",
  "epoxy-resin",
  "new-items",
]);
export type Category = z.infer<typeof categorySchema>;

export const CATEGORIES = categorySchema.options;

// Units seen across the real catalogue.
export const unitSchema = z.enum([
  "kg",
  "gram",
  "quintal",
  "tonne",
  "pack",
  "carton",
  "piece",
  "bag",
  "bottle",
  "dozen",
  "cubic-feet",
]);
export type Unit = z.infer<typeof unitSchema>;

// A wholesale/retail tier — how "Per Tonne / Per Kg / 100-pack" is modelled.
export const priceTierSchema = z.object({
  id: z.string().min(1),
  label: localizedSchema, // e.g. "Per Tonne", "100 Pack"
  packaging: localizedSchema, // e.g. "25 Kg Bag", "Carton of 100"
  unit: unitSchema,
  quantity: z.number().positive(), // numeric size in `unit`
  minOrderQty: z.number().int().positive().default(1),
  // Phase 0 is enquiry-driven, so price is hidden by default; the real value is
  // still stored so Phase 2 can switch it on without a re-scrape.
  priceOnEnquiry: z.boolean().default(true),
  price: z.number().nonnegative().optional(),
  inStock: z.boolean().default(true),
});
export type PriceTier = z.infer<typeof priceTierSchema>;

// One ingredient line — the QR info page's primary content (when present).
export const ingredientSchema = z.object({
  name: localizedSchema,
  note: localizedSchema.optional(),
});
export type Ingredient = z.infer<typeof ingredientSchema>;

// A specification row carried over from the source catalogue (bilingual key+value).
export const specSchema = z.object({
  label: localizedSchema,
  value: localizedSchema,
});
export type Spec = z.infer<typeof specSchema>;

export const productSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]+$/, "slug must be lowercase, digits, hyphens"),
  code: z.string().min(1), // short unique SKU, e.g. "BRQ-01"
  name: localizedSchema,
  category: categorySchema,
  brand: z.string().default("Ammedi"),
  shortDescription: localizedSchema,
  longDescription: localizedSchema,
  heroImage: z.string().min(1), // /products/<slug>/hero.<ext>
  images: z.array(z.string().min(1)).default([]),
  ingredients: z.array(ingredientSchema).default([]),
  specifications: z.array(specSchema).default([]),
  priceTiers: z.array(priceTierSchema).min(1, "at least one tier required"),
  hsnCode: z.string().optional(),
  featured: z.boolean().default(false),
  badges: z.array(localizedSchema).default([]),
  seo: z.object({ title: localizedSchema, description: localizedSchema }).optional(),
});
export type Product = z.infer<typeof productSchema>;

export const productsSchema = z.array(productSchema);
